import { NewArticle } from '../api/types';
import { uniqueToken } from '../support/seed';

/**
 * Build a fresh, unique NewArticle payload.
 *
 * The Conduit backend slugifies the title, so unique titles ⇒ unique slugs ⇒
 * no parallel-test collisions.
 */
export const articleFactory = {
  build(overrides: Partial<NewArticle> = {}): NewArticle {
    const token = uniqueToken();
    return {
      title: `QA Article ${token}`,
      description: 'A test article created by the QA framework.',
      body: `Body for article ${token}.\n\nGenerated by the test framework — safe to delete.`,
      tagList: ['qa', 'automated'],
      ...overrides,
    };
  },
};
